{
 "title": "Transactions Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "No Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time(({job=\"transactions-api\"} |~ \"HTTP/1.1\" !~ \" [45][0-9]{2} \")[5m])\r\n"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({job=\"transactions-api\"} |= \"HTTP/1.1\" |~ \" [45][0-9]{2} \" [5m])\r\n"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({job=\"transactions-api\"}[5m])\r\n\r\n\r\n"
    }
   ]
  }
 ]
}