version: '3.8'

services:
  transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql-db
      - loki

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: C@verinha.p4
      MYSQL_DATABASE: transactionsapi
      MYSQL_USER: transactions
      MYSQL_PASSWORD: transactions
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - C:/Users/caver/OneDrive/Documentos/csharp/Transactions-Api/loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

volumes:
  mysql_data:
  redis_data:
  loki-data: