version: '3.8'

services:
  transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactions-api
    ports:
      - "5000:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql-db:
        condition: service_started
      loki:
        condition: service_started
    volumes:
      - /var/log/transactions:/var/log/transactions
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: C@verinha.p4
      MYSQL_DATABASE: transactionsapi
      MYSQL_USER: transactions
      MYSQL_PASSWORD: transactions
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Web management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - ./loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log/transactions:/var/log/transactions
      - /tmp:/tmp
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  mysql_data:
  redis_data:
  loki_data:
  grafana_data:
  rabbitmq_data:
