services:
  transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactions-api
    ports:
      - "5000:80"
    depends_on:
      - mysql-db
      - loki
    volumes:
      - /var/log/transactions:/var/log/transactions # Volume para os logs do transactions-api

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: C@verinha.p4
      MYSQL_DATABASE: transactionsapi
      MYSQL_USER: transactions
      MYSQL_PASSWORD: transactions
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d  
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - ./loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning # Provisionamento automático de dashboards e datasources
      - ./grafana-data:/var/lib/grafana # Persistir dados do Grafana
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    ports:
      - "9080:9080" # Porta Promtail HTTP
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro # Arquivo de configuração do Promtail
      - /var/log/transactions:/var/log/transactions # Volume para os logs a serem coletados
      - /tmp:/tmp # Para armazenar posições do Promtail
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  mysql_data:
  redis_data:
  loki_data:
  grafana_data:
