server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: "transactions-api" # Nome do job
    static_configs:
      - targets:
          - localhost
        labels:
          job: "transactions-api"
          app: "transactions-api"
          host: "${HOSTNAME}"
          __path__: /var/log/transactions/*.log # Caminho dos arquivos de log
