name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar o .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Restaurar dependências
      - name: Restore Dependencies
        run: dotnet restore

      # Build da aplicação
      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      # Rodar testes
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Fazer login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker Image
        run: docker build -t fastcash-api:latest .

      # Publicar a imagem no Docker Hub
      - name: Push Docker Image
        run: docker tag fastcash-api:latest ${{ secrets.DOCKER_USERNAME }}/fastcash-api:latest && docker push ${{ secrets.DOCKER_USERNAME }}/fastcash-api:latest
